default_language_version:
    python: python3.9

default_stages: [commit, push]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: joint-line-ending
          - id: trailing-whitespace
          - id: check-toml
          - id: debug-statements

    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
        - id: black

    - repo: https://github.com/asottile/blacken-docs
      rev: 1.16.0
      hooks:
        - id: blacken-docs

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: 'v0.0.289'
      hooks:
        - id: ruff
          args: [ --fix, --exit-non-zero-on-fix ]
          exclude: ^Tests/

    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.16.1
      hooks:
        - id: gitleaks
