version: '3.7'

services:
  mongo:
    image: "mongo:5.0"
    container_name: assistant-mongo
    networks:
      - backend
    volumes:
      - ./mongo_data/data/db:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: "exit 0"
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 15s

  api:
    build:
      context: .
    image: assistant:latest
    container_name: assitant-api
    hostname: api
    ports:
      - '8001:8000'
    networks:
      - backend
    tty: true
    depends_on:
      - mongo
    env_file:
      - .env
    command: poetry run gunicorn apps.assistant.http.app:create_app --log-level info --access-logfile - --workers 1 --threads 10 --timeout 650 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000

  tests:
    image: assistant:latest
    container_name: assitant-tests
    depends_on:
      - mongo
    networks:
      - backend
    env_file:
      - .env
    command: "poetry run pytest Tests -k 'not paid'"
    volumes:
      - ./src:/home/python/code/src
      - ./Tests:/home/python/code/Tests

networks:
  backend:
    driver: 'bridge'
